### ISSUE TITLE
No I2C version of PCB is has a trace with no pad or hole

### ISSUE THREAD

**Issue by PeregrineXII** [Guitarman9119/Raspberry-Pi-Pico-#3]
Let me start by saying thanks for sharing this project!  I was trying to get the No I2C version of the board fabbed by JLCPCB and they contacted me with what they thought might be an error in the board. The asked, "As shown below, there is no pad and hole for the indicated trace, is that normal?"  I included the image they sent below. I thought you might want a heads up in case perhaps you had not tried to have this version fabbed.  I'm an admitted noob at PCB design, so I can't address the question one way or the other. I'm going to switch my order to the I2C version and see what happens.  Thanks again for sharing your work, I'm very excited to build this project!

![NoI2CError](https://user-images.githubusercontent.com/107624288/174066222-a6954590-9161-4da9-865b-ae64c48babac.png)

**Comment by Guitarman9119** [comment]
I checked now I rerouted the B3 so there was two routes the incomplete one like you said but is was correct 
<img width="170" alt="image" src="https://user-images.githubusercontent.com/14301045/174076493-02ac8a5e-74d5-47bb-87ea-2ae93e81342f.png">

it was routed here I will update it so it will not give anyone issues in the future.
Thank you for letting me know

**Comment by PeregrineXII** [comment]
Awesome, thanks for looking into this and for replying so quickly!

**Comment by Guitarman9119** [comment]
No problem! Thanks for letting me know.
