### ISSUE TITLE
i2c address returns as "[ ]"

### ISSUE THREAD

**Issue by mcjka** [Guitarman9119/Raspberry-Pi-Pico-#4]
I was trying to make some text display following your tutorial. I am on a Rasperry Pi Pico, and using a Lenovo Thinkpad T420S, on Ubuntu 22.04. While trying to scan for the i2c address, it will only print "[ ]". Is the code a whitespace, or is this a bug in your code?
![tempImage2o433r](https://user-images.githubusercontent.com/95513381/210670464-dda27903-5212-4489-8d51-00556a4cf17e.gif)

**Comment by Guitarman9119** [comment]
is the device connected properly? seems like the pico isn't reading
anything on the i2c bus

**Comment by mcjka** [comment]
i figured it out i just needed to scew the pentiometer. Thanks for trying to help me
